version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tasksecret
      POSTGRES_DB: bookstar
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./backend:/var/www/html:delegated
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d
    ports:
      - "8002:80"
    depends_on:
      - php

  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - php

volumes:
  pgdata:
